/* fixed.c — sine table generation + myriometer string formatting. */
#include "minicad/fixed.h"

/* The sine table. Two sourcing strategies:
 *   - TARGET (MINICAD_PSX): use the baked ROM const `fx_sintab` from
 *     src/foundation/sintab.c (generated by tools/gen_sintab.py). Zero boot-time
 *     trig, no int64 soft-divide pulled into the binary.
 *   - HOST tests: build the table once with libm at first use (keeps the host
 *     build self-contained, no dependency on the generated file).
 */
#ifdef MINICAD_PSX
extern const int32_t fx_sintab[SIN_LEN];
int32_t fx_isin(int32_t angle) { return fx_sintab[angle & SIN_MASK]; }
int32_t fx_icos(int32_t angle) { return fx_sintab[(angle + DEG90) & SIN_MASK]; }
#else
static int32_t s_sin[SIN_LEN];
static int s_sin_ready = 0;
#include <math.h>
static void build_table(void) {
    for (int i = 0; i < SIN_LEN; ++i) {
        double a = (double)i / SIN_LEN * 2.0 * 3.14159265358979323846;
        s_sin[i] = (int32_t)(sin(a) * FX_ONE + (a < 0 ? -0.5 : 0.5));
    }
    s_sin_ready = 1;
}
int32_t fx_isin(int32_t angle) {
    if (!s_sin_ready) build_table();
    return s_sin[angle & SIN_MASK];
}
int32_t fx_icos(int32_t angle) {
    if (!s_sin_ready) build_table();
    return s_sin[(angle + DEG90) & SIN_MASK];
}
#endif

char *mym_to_mm_str(mym_t v, char *out) {
    int neg = (v < 0);
    /* promote through 64-bit so INT_MIN is safe */
    uint32_t a = (uint32_t)(neg ? -(mym2_t)v : (mym2_t)v);

    char tmp[12];
    int n = 0;
    do { tmp[n++] = (char)('0' + (a % 10u)); a /= 10u; } while (a);
    while (n < 2) tmp[n++] = '0';      /* ensure >=1 digit before the point */

    int o = 0;
    if (neg) out[o++] = '-';
    for (int i = n - 1; i >= 0; --i) {
        out[o++] = tmp[i];
        if (i == 1) out[o++] = '.';    /* decimal point one place from right */
    }
    out[o] = '\0';
    return out;
}
