#!/usr/bin/env python3
"""Generate the 4096-entry 1.12 fixed-point sine table as a C const array.
Run at build time (or commit the output) so the target binary does ZERO
boot-time trig and pulls in no int64 soft-divide. Quarter-wave symmetry could
shrink this 4x; full table is emitted for lookup simplicity (8 KB rodata)."""
import math, sys
N, ONE = 4096, 4096
vals = [round(math.sin(i/N*2*math.pi)*ONE) for i in range(N)]
# clamp to int16 range (max is +/-4096, fits int16)
out = sys.stdout
out.write("/* AUTO-GENERATED by tools/gen_sintab.py — do not edit. */\n")
out.write("#include <stdint.h>\n")
out.write("const int32_t fx_sintab[4096] = {\n")
for i in range(0, N, 12):
    row = ",".join(str(v) for v in vals[i:i+12])
    out.write("  " + row + ",\n")
out.write("};\n")
